version: 0.2

env:
  variables:
    PG_HOST: database-1.cdbvnwblylki.us-east-2.rds.amazonaws.com
    PG_PORT: 5432
    PG_DBNAME: store_db
    SECRET_USER: postgres
    SECRET_PASSWORD: postgres

phases:
  install:
    commands:
      - echo "installing....."
      - yum update -y
      - amazon-linux-extras install epel -y
      - amazon-linux-extras install postgresql13 -y
  pre_build:
    commands:
      - echo "pre-build phase running...."
      - echo ${PG_HOST}:${PG_PORT}:${PG_DBNAME}:${SECRET_USER}:${SECRET_PASSWORD} > ~/.pgpass
      - chmod 600 ~/.pgpass
  build:
    commands:
      - echo "build phase running...."
      - cat ~/.pgpass | rev
      - echo "\dt" > /tmp/file
      - psql --host ${PG_HOST} --dbname ${PG_DBNAME} --username ${SECRET_USER} -f /tmp/file
      - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo "post build running...."
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*