version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "installing....."
  pre_build:
    commands:
      - echo "pre-build phase running...."
      - mvn clean
  build:
    commands:
      - echo "build phase running...."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "post build running...."
artifacts:
  files:
    - target/StoreApp-0.0.1-SNAPSHOT.war
  discard-paths: yes