version: 0.2

phases:
  install:
    commands:
      - echo "installing....."
  pre_build:
    commands:
      - echo "pre-build phase running...."
  build:
    commands:
      - echo "build phase running...."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "post build running...."
artifacts:
  files:
    - target/*.war