version: 0.2
phases:
  install:
    commands:
      - echo "installing...."
  pre-build:
    commands:
      - echo "pre-build phase running...."
  build:
    commands:
      - echo "build phase running...."
      - mvn clean prepare-package war:explode
  post-build:
    commands:
      - echo "post build running...."
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*